"""All available English and French languages."""

LANGUAGES: tuple[str, ...] = (
    "English",
    "English 2",
    "French French",
    "Canadian French",
    "English French",
    "Spanish",
    "GameStop",
    "Indonesian Spanish",
    "Indonesian English",
    "99.1% Pure Indonesian",
    "Sephirothonesion",
    "Caps Lock",
    "Greek",
    "Swedish Greek",
    "Zimbabwean",
    "Swedish",
    "Norwegian",
    "Swedish Norwegian",
    "White",
    "Biss",
    "Piss",
    "Bahamian",
    "Hindi",
    "Hungarian",
    "Hungarian English",
    "Hungarian French",
    "Hungarian Spanish",
    "Hungry Japan",
    "Japanese",
    "Latin",
    "Left South English",
    "Left South French",
    "Left Shoe",
    "Normal",
    "North English",
    "North English French",
    "North English Spanish French",
    "North English Spanish",
    "Santa",
    "Zulu",
    "Hawaiian",
    "Hawaiian English",
    "Hungry Japanese English",
    "Angry North English",
    "Brazilian",
    "Brazilian English",
    "Persian",
    "Armenian Atlantian",
    "Dr. Seussian",
    "Dr. Seussian English",
    "Joseph Stalin",
    "Joseph Stalin Greek",
    "Joseph Stalin Spanish",
    "Xi Jinping",
    "Xi Jinpin Greek",
    "Chinese",
    "Simplified Chinese",
    "Traditional Chinese",
    "Complicated Chinese",
    "Extreme Chinese",
    "Extra Cheese",
    "Compact Cheese",
    "Lighthearted German",
    "Arabic",
    "Arabic English",
    "Arabic French",
    "Arabic Spanish",
    "Arabic Spanish Greek",
    "Arabic Spanish Spanish Greek",
    "Arabic Spanish Spanish Spanish",
    "Arabic French Spanish",
    "Arabic French Spanish Greek",
    "Arabic French Spanish French",
    "Arabic French Spanish French Greek",
    "Critical Chinese",
    "Water-soluble Chinese",
    "Ballerina",
    "Permeable Chicago",
    "Permeable Chicago English",
    "Just Wired",
    "Unjust Wired",
    "Operational Chinese",
    "Wedding Chinese",
    "Boiling Chinese",
    "Fragrant Chinese",
    "Feelable Chinese",
    "John Lasnet",
    "John Lasnet Greek",
    "John Lasnet Spanish",
    "John Lasnet Spanish Greek",
    "Curated English",
    "Korean",
    "North Korean",
    "South Korean",
    "East Korean",
    "West Korean",
    "Northwest Korean",
    "Northeast Korean",
    "Southwest Korean",
    "Southeast Korean",
    "Sound of Hanging",
    "Hungarian Letters",
    "Alphabet",
    "Facebook",
    "Slurrish",
    "Slurrish English",
    "Slurrish English French",
    "Chinese Compacted",
    "Cum Dumpster",
    "Mutated Metanese",
    "Mega Crit",
    "White 2",
    "Line 116",
    "Gangnam",
    "Lard",
    "Bengali",
    "Bengali English",
    "Bengali Biss",
    "Bilirubin",
    "Bilirubin English",
    "Jaundice",
    "Jaundice English",
    "French Person",
    "Eardrum",
    "Good French",
    "Good French English",
    "Lamb Fried People",
    "Lamb Fried People English",
    "Reflected Kaan",
    "Reflected Kaan English",
    "Symbolism",
    "Love",
    "Body Odor",
    "Laggy's French",
    "Laggy's French English",
    "Wood's Waor",
    "Wood's Waor English",
    "Large Russian",
    "Unfortunate Russian",
    "Unfortunate Russian English",
    "Russian French",
    "Cool German",
    "Project Hail Mary",
    "Regional Language",
    "Regional Language English",
    "Festive Italian",
    "Festive Italian English",
    "Aggressive Bengali",
    "Aggressive Bengali English",
    "Aggressive Bengali English French",
    "Aggressive Bengali English Greek",
    "Aggressive Bengali English Spanish",
    "Aggressive Bengali Spanish Greek",
    "Goose Bengali",
    "Goose Bengali English",
    "Houses",
    "Houses City",
    "City Houses",
    "Gregor McFarlane",
    "Gregor McFarlane Greek",
    "Gregor McFarlane Spanish",
    "Gregor McFarlane Spanish Greek",
    "Gregor McFarlane Spanish Spanish",
    "Fishy Chinese",
    "Rotten Chinese",
    "Masturbation",
    "Yaoi Indonesia",
    "Yaoi Indonesia English",
    "Yaoi Indonesia English French",
    "Restraining Order",
    "Let Me Come In",
    "Excuse me, sir?",
    "This",
    "This",
    "This",
    "This",
    "This English",
    "This English French",
    "Let Me Come In",
    "Let Me Come In",
    "Ice Tycoon",
    "Verity",
    "Lord Verity",
    "Pregnancy",
    "Pregnancy English",
    "Pregnant Verity",
    "Pregnancy Verity English",
)