"""Tips displayed on the Home dashboard."""

TIPS: tuple[str, ...] = (
    "Laggy's in heat again.",
    "Use command [panic] for immediate results.",
    "Don't speak English? You can change your language settings by learning English!",
    "Would you take the left or the right.",
    "Press B to jump.",
    "If you think you exist, you probably do.",
    "Don't step into my house. Because you can't just tiptoe quiet as a mouse.",
    "Use the SephOrRadio to distract the monsters.",
    ":steamhappy:",
    "Contrary to popular belief, dynamite is NOT a kind of candle.",
    "*Does a sick backflip*",
    "Scheme all evil like.",
    "Remember to turn around occasionally to check for spies.",
    "Do not eat bricks.",
    "Urine is liquid waste that your kidneys make to remove excess fluids and "
    "waste products from your body.",
    "While falling from a great height, you can use a bucket of water right before you land. "
    "This won't do anything. Why would you think that would do anything?",
    "Sephiroth can rotate.",
    "2,000 calories is the recommended daily intake for the average person.",
    "I like mario kart.",
    "https://en.wikipedia.org/wiki/Family_Guy",
    "There is a 1% chance of your luggage exploding when you go to open it.",
    "LET IT RIDE.",
    "Micheal Jackson.",
    "That's kinda gay gojo.",
    "Don't ever buy no weed from no gas station.",
    "If you have to much negative karma, consider being nicer.",
    "Drink water.",
    "I ate a bagel today.",
    "Proceed.",
    "Do a funny little dance.",
    "Hey kid, you want some drugs?",
    "Legalize nuclear bombs.",
    "GUARDS!!! SEIZE THEM!!!",
    "I bet you don't have cool sunglasses like me.",
    "Don't check your mailbox.",
    "If you notice somebody following you home, they shouldn't be able to catch you, "
    "because I took their left shoe. I needed to replace the one that other asshole took.",
    "Five, Hundred, Tips.",
    "Put 'IN MINECRAFT' at the end of all your searches, so nobody suspects you.",
    "When playing pursuer in the new Die of Death update, it is imperative "
    "that you get good value out of your howl. This is because a strong howl can secure a kill "
    "without immediate intervention, allowing you to pick off members of the team.",
    "Also try minecraft.",
    "Your final challenge: let your fish go through your phone.",
    "you are now manually breathing.",
    "Tuna can? Tuna can what?",
    "You wanna know who else got turned into a tip? MY MOM!!!",
    "I, AM FUCKING, RENDERING SOMETHING, YOU COCK SUCKER.",
    "Are you fucking microwaving something?",
    "No it- it's Adrian drake.",
    "What do you call the thing that connects the ocean and the beach? (Let me come in).",
    "*Cloud Strife impressed*",
)
